### ISSUE TITLE
Fix Phantom Scrollbar Icon

### ISSUE THREAD

**Issue by jgordley** [opensourcesocialgames/website#14]
On the "Screenshots" page, a scrollbar arrow icon appears floating at the bottom right of the screen. Investigate and remove.
![what is this](https://user-images.githubusercontent.com/24211938/153456131-9ff944d1-c6cd-485e-a6d4-4848d2be6e90.JPG)

**Comment by jgordley** [comment]
Great! If you'd like you can check out our [website contribution page](https://partyfish.netlify.app/contribution) to see the rules for contributing.

**Comment by jgordley** [comment]
Pretty much just make a new branch, fix the issue, then make a pull request and one of us will review it and merge it in. Thanks for the help!

**Comment by furkanmutlu** [comment]
PR: https://github.com/partyfishgames/website/pull/15

**Comment by jgordley** [comment]
Ah I see that, sorry about that. Here is our site https://partyfish.netlify.app/ we are just getting the project started and we appreciate your help

**Comment by jgordley** [comment]
Would you like to be added as our first contributor on the 'About us' page? We can link your github!

**Comment by furkanmutlu** [comment]
Yeah sure, I would like to help in the future challenges as well. I will also join to your discord channel :) nice to meet you
